### ISSUE TITLE
develop branch behind main

### ISSUE THREAD

**Issue by MakisH** [precice/fmi-runner#12]
This is currently misleading/confusing.

**Comment by uekerman** [comment]
`develop` has no purpose AFAIU. I deleted the branch.

**Comment by uekerman** [comment]
Ahh, we need it here:

https://github.com/precice/precice.github.io/blob/0f93c645525351a7e9cd32a37a8727ba9847276b/.gitmodules#L17-L20

**Comment by MakisH** [comment]
We can simply change that to `main`, if indeed no `develop` branch is used here.

**Comment by uekerman** [comment]
https://github.com/precice/precice.github.io/pull/347
