### ISSUE TITLE
Port to preCICE v3

### ISSUE THREAD

**Issue by uekerman** [precice/fmi-runner#5]
Let's only merge this, once we released `v0.1.0`.
We should then also change to a branching workflow with dedicated `main` and `develop` branches and make `main` the default.

**Comment by LeonardWilleke** [comment]
The runner was modified in [branch](https://github.com/precice/fmi-runner/tree/port-v3) `port-v3` to run with both preCICE v2 and v3. The code works but was not extensively tested yet (mainly on the oscillator tutorial). However, this approach makes the code much less readable as a lot of if-else statements are included. 

Maybe it makes more sense to make a clear cut in version compatibility: FMI runner `v1.0.0` is only compatible with preCICE v3, while users interested in coupling to preCICE v2 can still use FMI runner `v0.1.0`

@uekerman Probably this was your intention all along and I misunderstood

**Comment by uekerman** [comment]
Yes, it's not necessary that one version supports both v2 and v3. Let's only take v3 and eventually release `v0.2.0` (no breaking changes from the perspective of the runner).

**Comment by uekerman** [comment]
closed by #9
